### ISSUE TITLE
the triggerbot not working

### ISSUE THREAD

**Issue by spartan2375** [C0reTheAlpaca/C0reExternal-Base-v2#1]
The triggerbot is no longer working after the update. Does anyone happen to know why?

**Comment by full-screen** [comment]
update Offsets

**Comment by spartan2375** [comment]
XD im not exactly that stupid (*cough cough* at least I hope) I updated the offsets using a combination of the haze dumper offsets on github (courtesy of HazeProductions) and the thread on unknowncheats... IDK why these offsets would not work.
Edit: lol ok I am that stupid, I replaced an F with an E. MB
